config:
  # This will be used for the documentroot and the vhost name
  # Documentroot will be /var/www/htdocs/projectname
  # Vhost will be dev.projectname.com and reachable on the private box ip
  project_name: 'projectname'
  private_box_ip: '192.168.56.75'
  # git clone $git_repo
  git_repo: '-b master git@github.com:symfony/symfony.git'
  timezone: 'Europe/Amsterdam'
  memory: "2048"
  cpus: "2"
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  vagrant_box: "ajnijland/php5-centos-nginx-mysql"
  vagrant_box_version: "0.1.0"

